### ISSUE TITLE
Melhoria: Criação Explícita de Arquivos .py

### ISSUE THREAD

**Issue by LiviaKarolayne** [Eds0nJun1or/1st-projeto-pratico-alura#1]
# Tarefas
- [x] #5
- [x] **Nomeação Significativa:** Dê nomes significativos aos arquivos .py para que sua funcionalidade seja clara. Por exemplo, "backup.py" para o script de backup e "limpeza_temporarios.py" para o script de limpeza de temporários.
- [x] **Estrutura de Diretórios Significativa:** Ao dividir o código em arquivos .py separados, é importante pensar também na estrutura de diretórios. Organize os arquivos em uma hierarquia de diretórios significativa que reflita a arquitetura e a funcionalidade do seu projeto.

## Um exemplo/suguestão de estrutura de diretórios:
```text
src/
├── backups/
│   └── backup.py
│   └── README.md
├── limpeza_temporarios/
│   └── limpeza_temporarios.py
│   └── README.md
├── monitoramento/
│   ├── disco.py
│   └── recursos.py
│   └── README.md
├── permissões/
│   └── permissões.py
│   └── README.md
├── atualização_pacotes.py
├── notificação_email.py
├── cron_rules.cron
└── README.md
```

**Comment by Eds0nJun1or** [comment]
Pronto Lívia, muito obrigado por este primeiro feedback, após reorganizar eu percebi que dentro das pastas ficou mais organizado e didático mesmo.

**Comment by LiviaKarolayne** [comment]
Show, Edson!
