### ISSUE TITLE
Melhoria: Refatoração de Código

### ISSUE THREAD

**Issue by LiviaKarolayne** [Eds0nJun1or/1st-projeto-pratico-alura#4]
# Tarefas
- [x] **Explicitação da Função Main:** A função [main](https://docs.python.org/pt-br/3/library/__main__.html) é o ponto de partida do nosso programa. Ela deve aparecer no código para indicar onde a execução começa. Ao definir essa função, deixamos claro o ponto inicial do nosso programa e como ele funciona. Isso torna o código mais fácil de entender, especialmente para iniciantes, pois fornece uma estrutura clara para o fluxo de execução.
- [x] **Remoção de Dados Sensíveis:** Senhas e dados sensíveis devem ser removidos do código-fonte e obtidos através de [variáveis de ambiente](https://awari.com.br/python-como-obter-variaveis-de-ambiente/?utm_source=blog&utm_campaign=projeto+blog&utm_medium=Python:%20Como%20obter%20vari%C3%A1veis%20de%20ambiente), seguindo as práticas recomendadas de segurança.
- [x] **Modularização do Código:** O código deve ser modularizado para torná-lo mais reutilizável e fácil de manter. Por exemplo, criar funções genéricas para operações repetitivas e reutilizáveis, como envio de e-mails.
- [x] **Adição de Log e Tratamento de Exceções:** É recomendável incluir [logging](https://www.hashtagtreinamentos.com/logging-em-python?gad_source=1&gclid=CjwKCAjww_iwBhApEiwAuG6ccLbfoGBuwVGU6htgL6ci3lVAYdoGJt7otP51a63NLHA86lZtq4d3NBoC7rQQAvD_BwE) e [tratamento de exceções](https://docs.python.org/pt-br/3/tutorial/errors.html) para tornar o código mais robusto e facilitar a identificação e resolução de problemas.
- [x] **Regras do Crontab em Arquivo Separado:** As regras do crontab podem ser mantidas em um arquivo cron separado para melhor organização e legibilidade do código.

**Comment by Eds0nJun1or** [comment]
Pronto Lívia, reorganizei o commit inteiro e creio que agora está seguindo um padrão com boas práticas.

**Comment by LiviaKarolayne** [comment]
Ótimo, Edson!

Além disso, é uma prática recomendada definir um arquivo "main.py" na raiz do projeto para organizar e definir o fluxo principal do script. Isso ajuda a manter a estrutura do projeto clara e fácil de entender para você e para outros colaboradores.
